### ISSUE TITLE
Cannot parse <->..</-> tags

### ISSUE THREAD

**Issue by platten** [sbraz/pymediainfo#1]
I have a few files  with data between <-></-> tags which upsets minidom. sample output from mediainfo is below:

<?xml version="1.0" encoding="UTF-8"?>
<Mediainfo version="0.7.48">
<File>
<track type="General">
<Complete_name>/mnt/smbshare/Hilemusic/Jazz/Miles Davis/Sketches Of Spain/01 Concierto de Aranjuez (Adagio).m4a</Complete_name>
<Format>MPEG-4</Format>
<Format_profile>Base Media / Version 2</Format_profile>
<Codec_ID>mp42</Codec_ID>
<File_size>27.9 MiB</File_size>
<Duration>16mn 23s</Duration>
<Overall_bit_rate>238 Kbps</Overall_bit_rate>
<Album>Sketches of Spain</Album>
<Album_Performer>Miles Davis</Album_Performer>
<Track_name>Concierto de Aranjuez (Adagio)</Track_name>
<Track_name_Position>1</Track_name_Position>
<Track_name_Total>8</Track_name_Total>
<Performer>Miles Davis</Performer>
<Genre>Jazz</Genre>
<Recorded_date>1997</Recorded_date>
<Encoded_date>UTC 2009-12-13 09:41:30</Encoded_date>
<Tagged_date>UTC 2011-05-02 16:51:20</Tagged_date>
<BPM>103</BPM>
<Cover>Yes</Cover>
<-> 0000014B 00000107 0000564D 0000B641 00049D0B 0007B384 00007FAC 000072E0 0007A21A 0007B4F8</->
<cddb>780e3b08</cddb>
</track>

<track type="Audio">
<ID>1</ID>
<Format>AAC</Format>
<Format_Info>Advanced Audio Codec</Format_Info>
<Format_profile>LC</Format_profile>
<Codec_ID>40</Codec_ID>
<Duration>16mn 23s</Duration>
<Bit_rate_mode>Variable</Bit_rate_mode>
<Bit_rate>234 Kbps</Bit_rate>
<Maximum_bit_rate>301 Kbps</Maximum_bit_rate>
<Channel_s_>2 channels</Channel_s_>
<Channel_positions>Front: L R</Channel_positions>
<Sampling_rate>44.1 KHz</Sampling_rate>
<Compression_mode>Lossy</Compression_mode>
<Stream_size>27.5 MiB (98%)</Stream_size>
<Writing_library>1.3.3.0 1.3.3.0</Writing_library>
<Encoding_settings>-q 0.60</Encoding_settings>
<Encoded_date>UTC 2009-12-13 09:41:30</Encoded_date>
<Tagged_date>UTC 2011-05-02 16:51:20</Tagged_date>
</track>

<track type="Menu">
</track>

</File>
</Mediainfo>

here is a quick and dirty fix: 
4a5
> import re
75c76
<             dom = minidom.parseString(xml_data)
---
>             dom = minidom.parseString(re.sub('<->[\\s\\d\\w]+</->', '', xml_data))

Cheers,
Paul

**Comment by sbraz** [comment]
Hi, can you provide me with the complete XML?

**Comment by sbraz** [comment]
No feedback, I'm closing this.
