### ISSUE TITLE
OSError: Failed to load library

### ISSUE THREAD

**Issue by Sh1vam** [sbraz/pymediainfo#103]
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pymediainfo/__init__.py", line 421, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
  File "/usr/local/lib/python3.9/dist-packages/pymediainfo/__init__.py", line 323, in _get_library
    raise OSError("Failed to load library")
OSError: Failed to load library
```

**Comment by sbraz** [comment]
Hello, can you tell me how you installed pymediainfo and how you installed the libmediainfo?

Did you read the note [here](https://pymediainfo.readthedocs.io/en/stable/)?
>  Without the library, this package cannot parse media files, which severely limits its functionality.
>    Binary wheels containing a bundled library version are provided for Windows and Mac OS X.
>    Packages are available for several major Linux distributions. They depend on the library most of the time and are the preferred way to use pymediainfo on Linux unless a specific version of the package is required.

**Comment by Sh1vam** [comment]
just i did  pip install pymediainfo

**Comment by sbraz** [comment]
What about libmediainfo? If you're using [any of the linux distributions listed here](https://repology.org/project/python:pymediainfo/versions), you should install pymediainfo from the distribution's official repository.

**Comment by Sh1vam** [comment]
is libmediainfo a python library .
ERROR: Could not find a version that satisfies the requirement libmediainfo
ERROR: No matching distribution found for libmediainfo

How to install it from https://repology.org/project/python:pymediainfo/versions

**Comment by sbraz** [comment]
No, it is not a Python library, it is a C library on which pymediainfo relies. You need to install it with your package manager (I can't guess which one you're using but if you're running Debian, it should be `apt install libmediainfo0v5` to get the library or `apt install python3-pymediainfo` to install pymediainfo).

**Comment by Sh1vam** [comment]
ohk thankyou sir
