### ISSUE TITLE
Permission denied: '/usr/local/docs'

### ISSUE THREAD

**Issue by pivdets** [sbraz/pymediainfo#104]
Go error

```shell
Installing collected packages: pymediainfo
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/docs'
Consider using the `--user` option or check the permissions.
```

When using `pip3 install pymediainfo`

**Comment by sbraz** [comment]
Hello, this is normal when running pip as non-root. You will see this error for any other package install.
As explained in the documentation, I recommend installing pymediainfo with your package manager [if your distribution offers it](https://repology.org/project/python:pymediainfo/versions).

**Comment by pivdets** [comment]
Thanks @sbraz , finally I made it works by `pip3 install pymediainfo --user` and set the Python path to add the local site-packages

`export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/lib/python/site-packages"`
