### ISSUE TITLE
OSError: Failed to load library; Error occurred in macOS version 11.0.1

### ISSUE THREAD

**Issue by austin-365** [sbraz/pymediainfo#106]
```
  File "video_info.py", line 44, in <module>
    meida_info = json.loads(MediaInfo.parse(os.path.join(file_path, item)).to_json()) #, output="json")
  File "/Library/Python/3.8/site-packages/pymediainfo/__init__.py", line 421, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
  File "/Library/Python/3.8/site-packages/pymediainfo/__init__.py", line 323, in _get_library
    raise OSError("Failed to load library")
OSError: Failed to load library
```

**Comment by austin-365** [comment]
I installed it by 'sudo pip3 install pymediainfo', but error occur.
I wonder how can I install libmediainfo in macOS.

**Comment by sbraz** [comment]
Hello,
What version did pip install? Can you show me the output of the pip command? There is a wheel (` pymediainfo-5.0.3-py3-none-macosx_10_9_x86_64.whl`) but maybe it's not compatible with MacOS 11.

**Comment by sbraz** [comment]
Please also check that you are running the latest pip version.

**Comment by austin-365** [comment]
> Please also check that you are running the latest pip version.


The old pip version is 19, and after I upgrade it, all things work! 
thank you sir!
