### ISSUE TITLE
build failure with setuptools_scm 6.0.1 on Python 2.7

### ISSUE THREAD

**Issue by kishan-ajudiya** [sbraz/pymediainfo#107]
Collecting pymediainfo==4.2.1
  Downloading pymediainfo-4.2.1.tar.gz (434 kB)
------------------------------------------------------------------------
      File "/tmp/easy_install-DpxMzQ/setuptools_scm-6.0.1/setup.py", line 52, in <module>
        setup_requires=["setuptools_scm"],
      File "/tmp/easy_install-DpxMzQ/setuptools_scm-6.0.1/setup.py", line 29, in scm_config
    
      File "/tmp/easy_install-DpxMzQ/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
      File "/tmp/easy_install-DpxMzQ/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
      File "/tmp/easy_install-DpxMzQ/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax

**Comment by sbraz** [comment]
Hi,
Python 2 is no longer supported [since v5.0](https://github.com/sbraz/pymediainfo/releases/tag/v5.0).

I understand you're trying to use an older version but I am not providing support for these. Your problem seems to be that `setuptools_scm` dropped old Pythons in 6.0 [as mentioned in their changelog](https://github.com/pypa/setuptools_scm/blob/main/CHANGELOG.rst#v600).

I would suggest you try to migrate your code to Python 3.

**Comment by mihalikv** [comment]
@sbraz I have a similar problem with pymediainfo==4.0 and python==3.5. Since setuptools_scm has not specified version and it drops support for python 3.5 you can be blocked. Try to upgrade to Python 3.6.

**Comment by sbraz** [comment]
@mihalikv I think you meant to mention @kishan-ajudiya.

**Comment by mihalikv** [comment]
@sbraz I hope that you correct me and send me some brilliant solution, that prevent me from an upgrade  😄 
Maybe someone will struggle with the same error and find this useful.

**Comment by sbraz** [comment]
@mihalikv You can just install an older version of `setuptools_scm` and pin it, no?

**Comment by mihalikv** [comment]
@sbraz something like this ?
setuptools_scm==5.0.2
pymediainfo==4.0

pymediainfo still use setuptools_scm-6.0.1

**Comment by sbraz** [comment]
`pymediainfo` doesn't force a `setuptools_scm` version. There is probably something weird about your pip or your Python setup, I'm afraid it's a bit out of the scope of the pymediainfo project.
