### ISSUE TITLE
OSError: Failed to load library

### ISSUE THREAD

**Issue by sunshineluoxh** [sbraz/pymediainfo#109]
media_info = MediaInfo.parse(video_path)
File "/home/xxx/anaconda3/lib/python3.6/site-packages/pymediainfo/__init__.py", line 421, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
File "/home/xxx/anaconda3/lib/python3.6/site-packages/pymediainfo/__init__.py", line 323, in _get_library
    raise OSError("Failed to load library")
OSError: Failed to load library

Ubuntu16.04   use pip install pymediainfo，install 5.0.3 version
Errors occur as above 
Pls share me  how to solve the errors， can  'sudo apt-get install -y libmediainfo-dev' solve this? 
If can but i don't have the root right, have any other solutions?
So sorry to interrupt ，looking forward to your reply， thanks

**Comment by sunshineluoxh** [comment]
After use "sudo apt install mediainfo" with root , the error solved ！thanks

**Comment by sbraz** [comment]
@sunshineluoxh Ubuntu also has a package for pymediainfo that would have pulled the right dependencies.

**Comment by sunshineluoxh** [comment]
> @sunshineluoxh Ubuntu also has a package for pymediainfo that would have pulled the right dependencies.

Yeah,can i install the package without the root right ? I don't want to install pymediainfo with the root right,thanks

**Comment by sbraz** [comment]
Then you need to get `libmediainfo.so` yourself and pass it to the `parse` method via the `library_file` parameter, please check [the documentation](https://pymediainfo.readthedocs.io/en/stable/).
