### ISSUE TITLE
when i use this pymediainfo, i meet some problem like that , see the picture below. it can't loading dylib. （python3.8 macOS 11.3）

### ISSUE THREAD

**Issue by EmotionalBeast** [sbraz/pymediainfo#115]
![image](https://user-images.githubusercontent.com/33860198/136645999-9b516dde-d2f2-4c95-95b2-22266d8bd8ac.png)

**Comment by sbraz** [comment]
Hi @EmotionalBeast. I'm closing this issue since you didn't answer, please reply if you'd like me to reopen it.
