### ISSUE TITLE
Mac Install issue:  ModuleNotFoundError: No module named 'pymediainfo'

### ISSUE THREAD

**Issue by texasmouse** [sbraz/pymediainfo#120]
Using MacOSX 12.2.1 (Monterey), Python 3.9.12, and trying to install pymediainfo for Sickrage.  I also purchased pymediainfo from App Store and downloaded the CLI and dyLib from your website.  I copied the 2 libmediainfo dylib files into /usr/local/lib.  When I try to run SR, I get:

```
Traceback (most recent call last):
  File "/Applications/SickRage/sickrage/__init__.py", line 340, in main
    from sickrage.core import Core
  File "/Applications/SickRage/sickrage/core/__init__.py", line 52, in <module>
    from sickrage.core.common import Quality, Qualities, EpisodeStatus
  File "/Applications/SickRage/sickrage/core/common.py", line 30, in <module>
    from sickrage.core.helpers.metadata import get_file_metadata, get_resolution
  File "/Applications/SickRage/sickrage/core/helpers/metadata.py", line 23, in <module>
    import knowit
  File "/usr/local/lib/python3.9/site-packages/knowit/__init__.py", line 27, in <module>
    from .api import know
  File "/usr/local/lib/python3.9/site-packages/knowit/api.py", line 6, in <module>
    from .providers import (
  File "/usr/local/lib/python3.9/site-packages/knowit/providers/__init__.py", line 7, in <module>
    from .mediainfo import MediaInfoProvider
  File "/usr/local/lib/python3.9/site-packages/knowit/providers/mediainfo.py", line 12, in <module>
    from pymediainfo import MediaInfo
ModuleNotFoundError: No module named 'pymediainfo'
```

I have been looking at similar, older issues, but I am not having any luck.  Do you have any suggestions?

Thanks!

**Comment by sbraz** [comment]
Hi,
> I also purchased pymediainfo from App Store

I have never put pymediainfo on the app store, do you mean MediaInfo?

> from your website

Same, I don't have a website, did you mean MediaInfo's?

>  Do you have any suggestions?

`pip install pymediainfo` should just work and install a `whl` file which contains the necessary MediaInfo `dylib`.

**Comment by texasmouse** [comment]
You are correct in the purchase and webpage I mentioned.  I was under the impression that it was also you.  Apologies as it seems that is not the case.

I have been using ‘pip3’ as opposed to ‘pip’.  I don’t have ‘pip’ installed.  When I do use pip3, it reports back that the ‘Requirement already Satisfied: pymediainfo in /usr/local/lib/python3.9/site-packages (5.1.0)’.

**Comment by sbraz** [comment]
Yes, you need to use the pip binary that corresponds to your Python version. Try to run `pip3 install --upgrade pymediainfo` to force it to replace the existing version. I never included this in the documentation because these steps aren't specific to pymediainfo. Any package available on PyPI can be installed with pip and there are probably good tutorials if you need help with this.

**Comment by sbraz** [comment]
I'm closing this as this issue hasn't been active for a while.
