### ISSUE TITLE
output="" for MediaInfo.parse is equivalent to -f

### ISSUE THREAD

**Issue by prestidigitonium** [sbraz/pymediainfo#123]
Hello, I'd like to print the vanilla mediainfo output.
Using `MediaInfo.parse(<file>, output="")` it returns the `mediainfo -f <file>` output string.
Is there a way to print the vanilla `mediainfo <file>` output?

**Comment by sbraz** [comment]
Hi,
As mentioned in https://pymediainfo.readthedocs.io/en/stable/pymediainfo.html#pymediainfo.MediaInfo.parse, you can use `full=False` for this.

**Comment by prestidigitonium** [comment]
ok, it wasn't very clear what was "additional tags", thank you.

**Comment by sbraz** [comment]
I think I used the help from the `mediainfo` CLI to write this:
```
--Full, -f                                  
                    Full information Display (all internal tags)
```

But I'll also mention in the doc that this is equivalent to the CLI's `-f`/`--full`.

**Comment by sbraz** [comment]
@evilsh3ll I've pushed an update to the doc in https://github.com/sbraz/pymediainfo/commit/5731861aa459590b1a7585a501cdabf28c9907d5:
![image](https://user-images.githubusercontent.com/4833332/204054074-c8360191-bbca-461d-8d46-c8825778687c.png)
