### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by apiszcz** [sbraz/pymediainfo#124]
Calling parse on some files is causing a segmentation fault and the python VM exits. Is there an approach to mitigate this unexpected exit? Perhaps a .verify method?
Thank you for the API.

Perhaps .can_parse is the option, will test.

**Comment by sbraz** [comment]
Hi, can you please attach one of these files? Does `mediainfo` also fail to parse them? What version of the library are you using?

**Comment by apiszcz** [comment]
Hi, unfortunately not, i will see how can_parse does with the next file i encounter that causes a segmentation fault.

**Comment by sbraz** [comment]
`can_parse` just checks that the library is usable. It does not take media files into account. Did you also check my other suggestions (try with the CLI, check the version of libmediainfo)?

**Comment by apiszcz** [comment]
The CLI (separate test on a different windows computer) 
MediaInfo Command line,
MediaInfoLib - v22.06
Processes and displays the information for the file successfully.

The version on system where the issue occurs
libmediainfo-dev/focal,now 19.09+dfsg-2build1 amd64 [installed]
libmediainfo0v5/focal,now 19.09+dfsg-2build1 amd64 [installed,automatic]

**Comment by sbraz** [comment]
> The version on Ubuntu / Linux system where the issue occurs

Can you please install the CLI mediainfo on it and see if it works? Also please try the version from the MediaInfo repositories: https://mediaarea.net/en/Repos

**Comment by apiszcz** [comment]
Will do, testing next.
libmediainfo-dev/focal 22.06-1 amd64 [upgradable from: 19.09+dfsg-2build1]
libmediainfo-doc/focal 22.06-1 all
libmediainfo0v5-dbg/focal 22.06-1 amd64
libmediainfo0v5/focal 22.06-1 amd64 [upgradable from: 19.09+dfsg-2build1]
mediainfo-dbg/focal 22.06-1 amd64
mediainfo-gui-dbg/focal 22.06-1 amd64
mediainfo-gui/focal 22.06-1 amd64
mediainfo/focal 22.06-1 amd64

**Comment by apiszcz** [comment]
NO similar issues yet, thank you.

**Comment by sbraz** [comment]
@apiszcz so the upgrade made pymediainfo work with the file with which it failed before? If so, I assume we can close this issue.
