### ISSUE TITLE
On Mac Os X

### ISSUE THREAD

**Issue by awaffle01** [sbraz/pymediainfo#125]
raise OSError(
OSError: Failed to load library from libmediainfo.0.dylib, libmediainfo.dylib - dlopen(libmediainfo.0.dylib, 0x0006): tried: 'libmediainfo.0.dylib' (no such file), '/usr/lib/libmediainfo.0.dylib' (no such file), '/Users/aarav/Desktop/pyGame_Computing_WA3/libmediainfo.0.dylib' (no such file), dlopen(libmediainfo.dylib, 0x0006): tried: 'libmediainfo.dylib' (no such file), '/usr/lib/libmediainfo.dylib' (no such file), '/Users/aarav/Desktop/pyGame_Computing_WA3/libmediainfo.dylib' (no such file)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x11fec4de0] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 800x800, 759 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

**Comment by sbraz** [comment]
Hello, If you would like to open an issue, please use a proper title, describe the issue you are facing and provide context such as code samples.

**Comment by awaffle01** [comment]
### **I am trying to use the library for a game and I am getting the following error**
raise OSError(
OSError: Failed to load library from libmediainfo.0.dylib, libmediainfo.dylib - dlopen(libmediainfo.0.dylib, 0x0006): tried: 'libmediainfo.0.dylib' (no such file), '/usr/lib/libmediainfo.0.dylib' (no such file), '/Users/aarav/Desktop/pyGame_Computing_WA3/libmediainfo.0.dylib' (no such file), dlopen(libmediainfo.dylib, 0x0006): tried: 'libmediainfo.dylib' (no such file), '/usr/lib/libmediainfo.dylib' (no such file), '/Users/aarav/Desktop/pyGame_Computing_WA3/libmediainfo.dylib' (no such file)


I have already tried download dylib files from another GitHub issue page but it is still not working

**Comment by sbraz** [comment]
How did you install pymediainfo? Did you use pip? The PyPI packages contain a version of the dylib that should work.

Did you attempt to pass `library_file=/path/to/libmediainfo.dylib` to the `parse` method? Your logs show that no dylib was found.
