### ISSUE TITLE
Configurable connection settings for remote `MediaInfo.parse`

### ISSUE THREAD

**Issue by cmahnke** [sbraz/pymediainfo#139]
Currently it's not possible to set connection settings (like timeout) using `MediaInfo.parse(url, **mediainfo_opts)`. If this is already possible, it's hard to find the documentation (might be replicated here https://github.com/sbraz/pymediainfo/blob/master/pymediainfo/__init__.py#L370).

The documentation of [MediaInfo](https://mediaarea.net/en/MediaInfo/Support/SDK/More_Info) doesn't seem to provide this either.

**Comment by sbraz** [comment]
@jeromemartinez I checked https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Reader/Reader_libcurl.cpp and I don't see anything related to timeouts. I guess the library doesn't support this at the moment?

**Comment by cmahnke** [comment]
Yes, that's what i'ver figured out as well. I solved it by looping as long as no `RuntimeException` isn't raised anymore. This also does a retry if there is another error.

**Comment by JeromeMartinez** [comment]
> I don't see anything related to timeouts. 

Right. I don't expose all libcurl options. I may do it in the future (no ETA).
