### ISSUE TITLE
Seg Fault 11 on OS X

### ISSUE THREAD

**Issue by apwelsh** [sbraz/pymediainfo#20]
The line:

lib.MediaInfoA_Open(handle, filename.encode('utf-8'), 0)

throws a Seg Fault 11 on OS X.  

I am having a hard time isolating the cause, and I am not familiar enough with C++ to understand the prototypes to know what is wrong with the arguments.  Is this possibly related to the version of MediaInfo? I am on version 0.7.82

**Comment by sbraz** [comment]
Can you try replacing this line with `lib.MediaInfoA_Open(handle, filename, 0)` and let me know if it works? The version of MediaInfo shouldn't be an issue.

**Comment by apwelsh** [comment]
I am running Python 2.7, and suspecting the encode was because it was written for python 3, so i tried that.  

I also tried removing the 0, since the .h file for the lib has a filename only version, and the same thing.  Dont sweat it.  I figured it was an implementation bug, but it may be an issue in the dylib file itself. 

Ill play with it some more, but i am a beginner at python so it may take some time.  When i figure it out, ill report the fix.

Armand
--Sent from iPhone

**Comment by sbraz** [comment]
Actually you should also remove the `b` prefix from strings, try applying that:
```diff
diff --git a/pymediainfo/__init__.py b/pymediainfo/__init__.py
index 11ee51e..5fbe0ee 100644
--- a/pymediainfo/__init__.py
+++ b/pymediainfo/__init__.py
@@ -73,10 +73,10 @@ class MediaInfo(object):
             lib = CDLL("libmediainfo.so.0")
         # Create a MediaInfo handle
         handle = lib.MediaInfo_New()
-        lib.MediaInfoA_Option(handle, b"CharSet", b"UTF-8")
-        lib.MediaInfoA_Option(None, b"Inform", b"XML")
-        lib.MediaInfoA_Option(None, b"Complete", b"1")
-        lib.MediaInfoA_Open(handle, filename.encode("utf8"), 0)
+        lib.MediaInfoA_Option(handle, "CharSet", "UTF-8")
+        lib.MediaInfoA_Option(None, "Inform", "XML")
+        lib.MediaInfoA_Option(None, "Complete", "1")
+        lib.MediaInfoA_Open(handle, filename, 0)
         lib.MediaInfo_Inform.restype = c_wchar_p
         xml = lib.MediaInfo_Inform(handle, 0)
         # Delete the handle

```
If it doesn't help, I'll try to get my hands on a Mac OS system today :)

**Comment by sbraz** [comment]
@apwelsh Have you had a chance to try that code?

**Comment by apwelsh** [comment]
Sorry, I thought i replied, i already tried that and several variations. I Was going to tinker some more and get back to you if i can solve the issue. But, currently i am still stuck. 

Armand
--Sent from iPhone

**Comment by sbraz** [comment]
Have you tried the examples from the lib itself, using
https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfoDLL/MediaInfoDLL.py
and
https://github.com/MediaArea/MediaInfoLib/blob/master/Source/Example/HowToUse_Dll.py
?
If they work and my module doesn't, it probably means I missed something.

**Comment by apwelsh** [comment]
thanks for the links.  The howToUser_Dll.py does not throw any exceptions, but it doesn’t really open any files.  I’ll dig into it more to try and get media info from a file.

**Comment by apwelsh** [comment]
I take it back, I couldn’t find the exmple.ogg, but I pointed the HotToUse_Dll.py to a movie file I have, and it did in fact work correctly.  So there is something being done wrong in your script.  I’ll dig into it more this weekend, and if I find a work around, I let you know.

**Comment by sbraz** [comment]
Hi, can you try again with the latest git version?  I think the fix for https://github.com/sbraz/pymediainfo/issues/25 might have fixed your problem too.

**Comment by apwelsh** [comment]
Thank you for taking the time to follow-up.  This does not fix the issue on the Mac.

I read the description of the case, and removing the third argument was something I had already tried originally, as I noticed the error syntax back then as well.

It has something to do with the difference between how you are linking the libraries vs how they link them in the sample you had me try in the past (which did work).  I know your method is substantially different, and I had planned to roll-up my sleeves and learn Python, but I have just not had the time. 

I will dig into it some more tonight, and I’ll let you know if I can get it to work.  

On the Mac, the error I get is:

File "/Library/Python/2.7/site-packages/pymediainfo/__init__.py", line 72, in parse
    lib = CDLL("libmediainfo.0.dylib")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)

So it has to do with how the dynamic library is being initialized.

**Comment by apwelsh** [comment]
I compared the CDLL statement in the test copy that works with yours, and the one that works has hard-coded "/usr/local/lib/libmediainfo.dylib”.  Changing __init__.py line 72 to this value loads the dylib, and throws a Seg Fault 11 which is what I was experiencing before.

**Comment by apwelsh** [comment]
I don’t know what the option does, or what it’s supported value are, but I remove the CharSet = UTF-8 option assignment before opening the file, and the segfault went away.

**Comment by sbraz** [comment]
Nice ! Can you try to run the tests (`python setup.py test`)? The UTF-8 option should be useful when files have unicode tags.

**Comment by apwelsh** [comment]
So i wasn't getting a seg fault after the change (upon the open call) but i wasnt getting the info.  I started comparing your code against MediaInfoDLL.py and found that some options are set using the ansi methods and some are performed using the non-ansi methods.  So i changed the set options to the ansi methods except charset optin to the non ansi method.  Now i can open the file.

When i try to get info, it returns a memory address, not the xml, so i (again borrowing from the other script) declared the definition of the functions to be called for both the ansi and non ansi methods, when it returns the info as a pointer to a char array or wchar array, i now get the seg fault.

I dont know too much about python, but comparing the type code solutions, i can see that my issues in your code is based on the shortcuts your takes by assuming certain conditions to be true.  

I think will just figure out how to implement the MediaInfoDLL.py for my purposes, because it works as-is.

Armand
--Sent from iPhone

**Comment by sbraz** [comment]
If you use Python 2, it shouldn't make a difference whether you use `b"string"` or `"string"`. I wish I could convince you to perform more tests but I guess I'll have to try and do that on my own :)

**Comment by apwelsh** [comment]
I can do more tests. I just dont want to be a burden.


Armand
--Sent from iPhone

**Comment by sbraz** [comment]
You're not, don't worry!

**Comment by apwelsh** [comment]
My laptop went to sleep, so i will try that tonight. Cannot risk doing this in the server until I get the seg fault issues resolved.

Armand
--Sent from iPhone

**Comment by apwelsh** [comment]
Same seg fault with the ,0 (3rd argument) add to open.


I used the pip to install the library, so I don’t have the test.py.  I’ll clone Github to get the full suite and try the test on Saturday.

Thanks again

**Comment by sbraz** [comment]
I think I found the problem in my code thanks to https://github.com/sbraz/pymediainfo/issues/26
Can you please test the latest git version?

**Comment by apwelsh** [comment]
Sure.  Happy to give it try. 

Armand
--Sent from iPhone

**Comment by apwelsh** [comment]
Yay!  Its fixed now.  Now I need to learn how to use it.  The only remaining issue is the CDLL dies not work on My OS X without changing the path to full path "/usr/local/lib/libmediainfo.dylib"

Armand
--Sent from iPhone

**Comment by apwelsh** [comment]
Almost forgot, i also changed from .0.dylib to .dylib as on Mac the version is not in the name for this library.

Armand
--Sent from iPhone

**Comment by sbraz** [comment]
The Mac version is called `libmediainfo.0.dylib`, check http://mediaarea.net/download/binary/libmediainfo0/0.7.84/MediaInfo_DLL_0.7.84_Mac_i386+x86_64.tar.bz2
If it's not named like this, you probably downloaded it elsewhere.
As for the full path, it seems you're using the correct location: http://stackoverflow.com/a/31148541
I'll close the issue now, feel free to re-open it if you think I need to allow users to select the full path for the library but from what I understand, I don't think it's necessary.

**Comment by apwelsh** [comment]
Just so you know, i downloaded the gui client and the CLI client.  They both only provide libmediainfo.dylib, neither uses .0.dylib naming convention.  I have downloaded them from the app store, and the developer web site.  In all cases its without the "0".

Armand
--Sent from iPhone

**Comment by sbraz** [comment]
Fair enough :) I just added this to the code: https://github.com/sbraz/pymediainfo/commit/e08ab1b77f72336f868fafc4d87b0ef36d703ac4

**Comment by apwelsh** [comment]
For what its worth, i did not know about the DLL only download option until your message.

Armand
--Sent from iPhone
