### ISSUE TITLE
Mediainfo return empty list  in flask when debug=True

### ISSUE THREAD

**Issue by liangchaob** [sbraz/pymediainfo#21]
I use pymediainfo 2.0 in mac and ubuntu ,I put a video in the same directory , wanna get it's information , this function works well in the __main__, but once I wanna use it in flask ,the function will return nothing , did I miss something?

    # -*- coding: UTF-8 -*-

    import sys
    sys.path.append("./")
    reload(sys)
    sys.setdefaultencoding( "utf-8" )

    import os

    import time

    from flask import Flask, render_template, request, redirect, url_for ,jsonify

    from pymediainfo import MediaInfo

    def t_media():
        print os.listdir('.')
        media_info = MediaInfo.parse('cisco.mp4')
        print media_info.tracks

        for track in media_info.tracks:
            if track.track_type == 'Video':
                Duration = track.duration
                print str(Duration/1000.0)+' sec'
        else:
            Duration = 'none'
        return Duration

    app = Flask(__name__)

    @app.route('/')
    def index():
        return t_media()

    if __name__ == '__main__':

        app.run(host='0.0.0.0',port=8080,debug=True)

it return 'none' in the web, and my Server cli got this:

    # python test2.py
     * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
     * Restarting with stat
    ['.DS_Store', 'cisco.mp4', 'static', 'templates', 'test2.py', 'web.py']
    []
    172.16.191.1 - - [01/Mar/2016 16:08:44] "GET / HTTP/1.1" 200 -

**Comment by sbraz** [comment]
I actually have a segfault when I do a GET on /, I'll look into it.

**Comment by sbraz** [comment]
I think this has to do with Werkzeug's debugger: If I run the app with `debug=False` or with gunicorn, I don't have a problem.
Can you confirm this? Maybe you should file an issue there.

**Comment by liangchaob** [comment]
Thank you for response, I try it  by werkzeug and  I found my mistake, When I use 'for' circle , I should't add  'else'
the for circle would continue, and renew 'Duration'

fix:

    # -*- coding: UTF-8 -*-

    import sys
    sys.path.append("./")
    reload(sys)
    sys.setdefaultencoding( "utf-8" )

    import os

    import time

    from flask import Flask, render_template, request, redirect, url_for ,jsonify

    from pymediainfo import MediaInfo

    def t_media():
        print os.listdir('.')
        media_info = MediaInfo.parse('Cisco.mp4')
        print media_info.tracks

        for track in media_info.tracks:
            if track.track_type == 'Video':
                Duration = track.duration
                print str(Duration/1000.0)+' sec'

            return str(Duration)


    app = Flask(__name__)

    @app.route('/')
    def index():
        return t_media()


    if __name__ == '__main__':
        print t_media()
        app.run(host='0.0.0.0',port=8080)

Thank's a lot!

**Comment by liangchaob** [comment]
I have confirmed that when I run Flask in 'debug=False',it works well ,when I open the debug,it return an empty list.

```
# -*- coding: UTF-8 -*-

import sys
sys.path.append("./")
reload(sys)
sys.setdefaultencoding( "utf-8" )

import os

import time

from flask import Flask

from pymediainfo import MediaInfo

app = Flask(__name__)

@app.route('/')
def index():
    media_info = MediaInfo.parse('hehe.mp4')
    print media_info.tracks[0].duration
    return 'hehe'


if __name__ == '__main__':
    app.run(host='0.0.0.0',port=8080,debug=False)

```

It cause by the flask debug option

**Comment by sbraz** [comment]
Yeah it's probably a good idea to keep it opened.

**Comment by Hukuta** [comment]
same problem in django with development server:

in tests all is ok, but on development server variable "xml" is allways empty string

        handle = lib.MediaInfo_New()
        lib.MediaInfoA_Option(handle, b"CharSet", b"UTF-8")
        lib.MediaInfoA_Option(None, b"Inform", b"XML")
        lib.MediaInfoA_Option(None, b"Complete", b"1")
        lib.MediaInfoA_Open(handle, filename.encode("utf8"), 0)
        lib.MediaInfo_Inform.restype = c_wchar_p
        xml = lib.MediaInfo_Inform(handle, 0)

**Comment by sbraz** [comment]
I've pushed a fix, please let me know if it works as expected and I'll make a new release.
