### ISSUE TITLE
tracks only works in some cases, xml empty

### ISSUE THREAD

**Issue by eamonnkenny** [sbraz/pymediainfo#23]
mediainfo -f --Output=XML filename.webm works fine.
but since latest pip upgrade of pymediainfo from 1.4.0 to 2.0 finding that tracks information doesn't exist anymore. Well in fact dom is empty upon loading when it clearly isn't when running mediainfo.

Tried a different machine with 1.4.0 installed and worked on same file. Then upgraded using pip to 2.0 and found that same file fails.

Try downloading: http://peep.scss.tcd.ie/WebContent/corpus/dail_files/20080520_LCb/20080520_LCb.webm as a test case. Note, xmlwf shows XML from mediainfo is well-formed.

**Comment by sbraz** [comment]
This seems to be an issue with Python 2. It works fine with Python 3.
It might be related to https://github.com/sbraz/pymediainfo/issues/22 which is also something that fails on Python 2 but not Python 3. I have not yet been able to identify the issue.
Version 2.0 does not call the binary but relies on the library. If you want to mimic the old behaviour until it is fixed, you can do something like `pymediainfo.MediaInfo(subprocess.check_output(["mediainfo", "--output=XML", "-f", "20080520_LCb.webm"]))`

**Comment by sbraz** [comment]
The problem was with the unicode characters in the XML output. Please try with the git version (`pip install -U --user git+https://github.com/sbraz/pymediainfo/`)
