### ISSUE TITLE
ValueError in MediaInfo.parse

### ISSUE THREAD

**Issue by BlackOverlord666** [sbraz/pymediainfo#25]
It breaks on line `lib.MediaInfoA_Open(handle, filename.encode("utf8"), 0)` and says "Procedure probably called with too many arguments (4 bytes in excess)". I have just downloaded last version (0.7.84) of MediaInfo.
Quick look at sources of MI points me that API of dll is changed - function MediaInfoA_Open now takes only two arguments, so removing last argument in the call makes it work.

**Comment by sbraz** [comment]
I can not reproduce with 0.8.4 but it's true that the function seems to only take 2 args: https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfoDLL/MediaInfoDLL.cpp#L379
I cannot remember where the third argument came from.
I've pushed the change, thanks for the report.
