### ISSUE TITLE
cxfreeze can't find pymediainfo module?

### ISSUE THREAD

**Issue by gqhaha** [sbraz/pymediainfo#32]
I put pymediainfo name in cxfreeze's setup.py,but always show pkg_resources.DistributionNotFound: The 'pymediainfo' distribution was not found and is required by the application. 
can you help me for this ? thank you so much

**Comment by sbraz** [comment]
That looks like a problem with cxfreeze or you just don't have pymediainfo installed. I can't really help you without additional info.

**Comment by sbraz** [comment]
Hi, I'll have to close this. Please comment if you have more info to provide and I'll re-open.
