### ISSUE TITLE
How to determine libmediainfo is installed?

### ISSUE THREAD

**Issue by madebr** [sbraz/pymediainfo#34]
Currently, when libmediainfo is not installed, pymediainfo imports fine.
At parse time, an OSError is thrown when libmediainfo is not found.

Is there a portable (supported) way to determine pymediainfo is working as intended?
Depending on throwing an OSError that pymediainfo is not working is, in my opinion, not robust.

As a workaround, what I do now is:

```
import os.path
import pymediainfo # Succeeds since pymediainfo is installed

try:
    pymediainfo.MediaInfo.parse(os.path.realpath(__file__)
    libmediainfo_available = True
except OSError:
    libmediainfo_available = False
```

But I doubt this is kosher and supported.

**Comment by sbraz** [comment]
Well we don't really need libmediainfo in order to parse the XML files it created…

**Comment by madebr** [comment]
How about a `can_parse` static member function of the `MediaInfo` class? (or something similar)
What I want is a way to check whether parsing works before doing any actual parsing.

Something like this:
```
class MediaInfo(object):
    @classmethod
    def _get_library(cls):
        if os.name in ("nt", "dos", "os2", "ce"):
            return windll.MediaInfo
        elif sys.platform == "darwin":
            try:
                return CDLL("libmediainfo.0.dylib")
            except OSError:
                return CDLL("libmediainfo.dylib")
        else:
            return CDLL("libmediainfo.so.0")

    @classmethod
    def can_parse(cls):
        try:
            cls._get_library()
            return True
        except:
            return False
```

**Comment by sbraz** [comment]
That sounds reasonable, yeah. I'm not too experienced with staticmethod/classmethod, any reason why you chose the latter?

**Comment by madebr** [comment]
I chose classmethod where the method needs information about the class.
Staticmethod where it does nog.
So _get_library is ok with staticmethod (different from my code),
the can_parse has some connection with MediaInfo.

It's a matter of choice. The code would also work with 2 staticmethods.
