### ISSUE TITLE
Test file readable breaks URLs

### ISSUE THREAD

**Issue by cbricedavis** [sbraz/pymediainfo#36]
This commit: 

https://github.com/sbraz/pymediainfo/commit/938727f5e04e8a029eb3914939128970adaa21ac

causes checking URLs via mediainfo to break (it performs an open on the input - when the input is a URL it causes an IO error)

**Comment by sbraz** [comment]
I had no idea mediainfo parsed URLs. I'll fix this.

**Comment by sbraz** [comment]
Can you please try [the URLs branch](https://github.com/sbraz/pymediainfo/tree/urls)?
It should work for you. If it does, I'll add tests and release a new version.

**Comment by cbricedavis** [comment]
Works great!
