### ISSUE TITLE
Broke on Windows

### ISSUE THREAD

**Issue by issamu2k** [sbraz/pymediainfo#37]
I've tried on Windows 7 and 10, lastest mediainfo installed and still it's broken here:
windll.MediaInfo from _get_library

I had to overload and manually load from installation path.

**Comment by sbraz** [comment]
Do you mean it can't locate the DLL? I believe it has to be in a system folder or the current folder.

**Comment by sbraz** [comment]
Hi, I'm closing this issue. Please reply if you have some feedback.
