### ISSUE TITLE
Handling of special Characters leads to exception

### ISSUE THREAD

**Issue by mirgleich** [sbraz/pymediainfo#38]
When having for example ä, ö, ü or & and some others are throwing a ctypes.ArgumentError: argument 2: <type 'exceptions.UnicodeDecodeError'>: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)

**Comment by sbraz** [comment]
What Python version, what libmediainfo version?

**Comment by sbraz** [comment]
What pymediainfo version, where are the special characters? In the file name? In the metadata?

**Comment by mirgleich** [comment]
The special Characters are in the file name. 
I am using Python 2.7.13 and pymediainfo in version 2.1.9

**Comment by sbraz** [comment]
What about libmediainfo? Can you run pymediainfo's tests? What OS are you running?

**Comment by mirgleich** [comment]
I am running an 64-bit arch Linux. 
I'm not that good in Python but if you tell me how to run that test I can sure.

**Comment by sbraz** [comment]
Download pymediainfo [here](https://github.com/sbraz/pymediainfo/archive/v2.1.9.tar.gz), extract it and run `python2 setup.py test` (can't hurt to do it with python3 too).
I normally test files with special characters so you should see a test failure.

**Comment by mirgleich** [comment]
I now ran both:11:23:55 ~/Downloads/pymediainfo (master *=)$ python2 setup.py test
running test
Searching for nose
Reading https://pypi.python.org/simple/nose/
Downloading https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b
Best match: nose 1.3.7
Processing nose-1.3.7.tar.gz
Writing /tmp/easy_install-PzmwBf/nose-1.3.7/setup.cfg
Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-PzmwBf/nose-1.3.7/egg-dist-tmp-1j2z6P
no previously-included directories found matching 'doc/.build'
creating /home/david/Downloads/pymediainfo/.eggs/nose-1.3.7-py2.7.egg
Extracting nose-1.3.7-py2.7.egg to /home/david/Downloads/pymediainfo/.eggs

Installed /home/david/Downloads/pymediainfo/.eggs/nose-1.3.7-py2.7.egg
running egg_info
creating pymediainfo.egg-info
writing pymediainfo.egg-info/PKG-INFO
writing namespace_packages to pymediainfo.egg-info/namespace_packages.txt
writing top-level names to pymediainfo.egg-info/top_level.txt
writing dependency_links to pymediainfo.egg-info/dependency_links.txt
writing manifest file 'pymediainfo.egg-info/SOURCES.txt'
reading manifest file 'pymediainfo.egg-info/SOURCES.txt'                                                                                                                                                                                                                       
reading manifest template 'MANIFEST.in'                                                                                                                                                                                                                                        
warning: no previously-included files found matching '.*'                                                                                                                                                                                                                      
warning: no previously-included files matching '__pycache__' found anywhere in distribution                                                                                                                                                                                    
warning: no previously-included files matching '*.py[co]' found anywhere in distribution                                                                                                                                                                                       
writing manifest file 'pymediainfo.egg-info/SOURCES.txt'                                                                                                                                                                                                                       
running build_ext                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                               
----------------------------------------------------------------------                                                                                                                                                                                                         
Ran 0 tests in 0.006s                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                               
OK                                                                                                                                                                                                                                                                             
11:24:12 ~/Downloads/pymediainfo (master *%=)$ python3 setup.py test                                                                                                                                                                                                           
running test                                                                                                                                                                                                                                                                   
Searching for nose                                                                                                                                                                                                                                                             
Reading https://pypi.python.org/simple/nose/                                                                                                                                                                                                                                   
Downloading https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b                                                                                                         
Best match: nose 1.3.7                                                                                                                                                                                                                                                         
Processing nose-1.3.7.tar.gz                                                                                                                                                                                                                                                   
Writing /tmp/easy_install-k2gjveu2/nose-1.3.7/setup.cfg                                                                                                                                                                                                                        
Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-k2gjveu2/nose-1.3.7/egg-dist-tmp-2eucnh8m                                                                                                                                                                
no previously-included directories found matching 'doc/.build'                                                                                                                                                                                                                 
creating /home/david/Downloads/pymediainfo/.eggs/nose-1.3.7-py3.6.egg                                                                                                                                                                                                          
Extracting nose-1.3.7-py3.6.egg to /home/david/Downloads/pymediainfo/.eggs

Installed /home/david/Downloads/pymediainfo/.eggs/nose-1.3.7-py3.6.egg
running egg_info
writing pymediainfo.egg-info/PKG-INFO
writing dependency_links to pymediainfo.egg-info/dependency_links.txt
writing namespace_packages to pymediainfo.egg-info/namespace_packages.txt
writing top-level names to pymediainfo.egg-info/top_level.txt
reading manifest file 'pymediainfo.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.*'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
writing manifest file 'pymediainfo.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.008s

OK
11:24:37 ~/Downloads/pymediainfo (master *%=)$

**Comment by sbraz** [comment]
Huh, it doesn't seem to find the tests, can you see them in `tests/test.py`?

**Comment by mirgleich** [comment]
I now ran the test on Both Python 2 and 3 and got no failure
[testoutput.txt](https://github.com/sbraz/pymediainfo/files/1084456/testoutput.txt)

Yes that was my mistake now it works

**Comment by sbraz** [comment]
Try installing `python2-pytest` and running `PYTHONPATH=. py.test2  tests/test.py`.

**Comment by sbraz** [comment]
OK, then I guess the problem may not be with pymediainfo but with your code. Try running `python2 demo.py tests/data/accentué.txt`. Does it work? If it does, you may be missing something encoding-related in your code.

**Comment by mirgleich** [comment]
yes that works. So I will check if I can fix it in my code. 
Thanks a lot
