### ISSUE TITLE
Pathlib support

### ISSUE THREAD

**Issue by abjugard** [sbraz/pymediainfo#40]
pymediainfo does not support Pathlib currently. It can be worked around by presenting the Pathlib object as a string, but since pymediainfo is all about accessing media file information it would make sense for the MediaInfo class to be able to accept a Pathlib object in its constructor.

**Comment by sbraz** [comment]
That's a good idea :) I'll fix something up as soon as I have a little time.

**Comment by sbraz** [comment]
Please try the pathlib branch, it should work as expected for you.

**Comment by abjugard** [comment]
Indeed, works exactly as I expected it to. Thank you!
