### ISSUE TITLE
issue with mediainfo 17.10?

### ISSUE THREAD

**Issue by bturkus** [sbraz/pymediainfo#41]
hi,
first, I just wanted to say that pymediainfo is the best! thanks for all your hard work! I'm not sure if I've discovered an issue, but I've found that some custom scripts designed to pull specific mediainfo values have stopped working with an upgrade to mediainfo version 17.10. If I roll back to 0.7.99_1, I don't seem to have the same problem. I'm on macOS El Capitan, and python 3.6.3. 

The values I'm looking to pull are all in the General track, and with the switch everything is coming up as NoneType. I hope that's enough info; if I've missed anything, please let me know.

And thanks again!

**Comment by sbraz** [comment]
So the tracks are still present but the values come out empty? You're using the latest version, right?
Can you upload a sample file?

**Comment by bturkus** [comment]
that totally worked! sorry,I'm an idiot. thanks for the quick response.
