### ISSUE TITLE
Failed to use on windows 10

### ISSUE THREAD

**Issue by lazylazypig** [sbraz/pymediainfo#45]
hi, all
I have installed pymediainfo with command "pip install pymediainfo", and I got the information as follow:
Successfully built pymediainfo
Installing collected packages: pymediainfo
Successfully installed pymediainfo-2.2.0

so, it seems pymediainfo has been installed correctly. I wrote a very simple example to test it:
import pymediainfo
fileInfo = pymediainfo.MediaInfo.parse(r'D:\test.jpg')
...

then I got some errors as follow:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\pymediainfo\__init__.py", line 176, in parse
    lib = cls._get_library(library_file)
  File "D:\Anaconda3\lib\site-packages\pymediainfo\__init__.py", line 142, in _get_library
    return windll.MediaInfo
  File "D:\Anaconda3\lib\ctypes\__init__.py", line 417, in __getattr__
    dll = self._dlltype(name)
  File "D:\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

how can i fix this problem ? thanks very much :)

**Comment by sbraz** [comment]
Hello, did you read this? https://pymediainfo.readthedocs.io/en/latest/#requirements
Did you put the DLL in the current folder or one of the Windows system folders?

**Comment by lazylazypig** [comment]
@sbraz I'm sorry for my carelessness. With your guide I have fixed the problem and it works well on windows. thanks :)
