### ISSUE TITLE
some values that have duplicate tags not being returned in tracks or to_json

### ISSUE THREAD

**Issue by 3lixy** [sbraz/pymediainfo#46]
```
$ pip2.7 freeze | grep pymed
pymediainfo==2.2.0

$ python2.7 -V
Python 2.7.9

$ mediainfo --version
MediaInfo Command line,
MediaInfoLib - v0.7.70
```

I was working out why the track.display_aspect_ratio from pymediainfo was returning 2.388 and the desktop mediainfo app was showing 2.40 : 1. I saw that the raw xml output from the library used by pymedianfo had both 2.388 and 2.40 : 1. The to_json also had only 2.388.

I have modified pymedinfo to allow it to return the raw xml after the file being parsed and then in my app using xmltodict to convert the raw xml into a dict so i can choose which value i want from multiple tags with the same name.

i.e. the output from xmltodict for u'Display_aspect_ratio' is
 [u'2.388', u'2.40:1'],

simply i added:
`self.xml = xml`
under 
`def __init__(self, xml):`

and at the bottom of the MediaInfo added
```
def raw_xml(self):
    return self.xml
```

Should I send a pull request?

Has anyone found this issue before and if so how was it solved?

**Comment by sbraz** [comment]
This isn't really an issue, all tags with multiple values are prefixed with `other_`:
```
 'display_aspect_ratio': '1.778',
 'other_display_aspect_ratio': ['16:9'],
```
This is documented [here](https://pymediainfo.readthedocs.io/en/latest/pymediainfo.html#pymediainfo.Track).

**Comment by 3lixy** [comment]
okies fair enough
