### ISSUE TITLE
Debian packaging in progress

### ISSUE THREAD

**Issue by anarcat** [sbraz/pymediainfo#47]
Hi!

This is a friendly notice to let you know that [Debian](https://debian.org/) is working on packaging your software for Debian. You can follow the progress of that work in [bug #867801](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867801) in the Debian Bug Tracking System (BTS).

The source code for the Debian package is in [this git repository](https://anonscm.debian.org/cgit/python-modules/packages/pymediainfo.git/). It will be uploaded into Debian shortly, at which point it will end up in the [NEW queue](https://ftp-master.debian.org/new.html) for legal review. Once the NEW process is completed, it takes about 10 days for the package to trickle down into "testing", which will become the next Debian release. This means your software will eventually be shipped in a "long term support" release, which last from three to five years, according to the [current statistics](https://wiki.debian.org/DebianReleases#Production_Releases).

If you are interested in maintaining the package yourself upstream, that is definitely possible. You can either upload the package yourself if you are a Debian member or I can act as a sponsor when a new release is published.

This is just a notification, but can also act as a coordination point for upstream packaging if you wish to followup on this. otherwise, feel free to close this issue whenever you like.

**Comment by sbraz** [comment]
Hi! Thanks for adding this package to Debian :) Let me know if you need me to do anything.

**Comment by anarcat** [comment]
So far so good: the package just got accepted in NEW which means it's now in "unstable" and will trickle down in testing if all goes well in 10 days.

The only comment I got from the NEW review is that "docs/conf.py also mentions Patrick Altman", presumably because that's not reflected in setup.py... Is that a person that worked on the documentation?

Thanks!

**Comment by sbraz** [comment]
He is the author of pymediainfo and I took up maintenance of the package when he stopped. I think he is mentioned in the licence too.

**Comment by anarcat** [comment]
okay, then I'll need to fix the copyright file. thanks for the clarification!

also note that you can keep track of Debian package updates and bug reports in the [tracker page](https://tracker.debian.org/pkg/pymediainfo). The package also shows up in the [repology page](https://repology.org/metapackage/python:pymediainfo/versions) as up to date, in case you want to keep track of versions or show badges.
