### ISSUE TITLE
empty xml if filename is in utf-8

### ISSUE THREAD

**Issue by legrostdg** [sbraz/pymediainfo#5]
Hi,

There seems to be an issue with filenames in utf-8
 
    >>> from pymediainfo import MediaInfo
    >>> media_info = MediaInfo.parse('Les shadoks - 4 - Quatrième série : BU-GA « Les Shadoks et le big blank » (2000).avi')
    >>> len(media_info.tracks)
    0
    >>> media_info.to_data()
    {'tracks': []}

When changing removing "env=environment" from the line 106 of pymediainfo/__init__.py
    
    p = Popen(command, stdout=fp_out, stderr=fp_err)

it seems to work:

    >>> from pymediainfo import MediaInfo
    >>> media_info = MediaInfo.parse('Les shadoks - 4 - Quatrième série : BU-GA « Les Shadoks et le big blank » (2000).avi')
    >>> len(media_info.tracks)
    3
    >>> media_info.to_data()
    {'tracks': [{'writing_application': u'MEncoder 2:0.99+1.0pre7try2+cvs20060117-0ubuntu8', 'file_name': u'Les shadoks - 4 - Quatri\xe8me s\xe9rie : BU-GA \xab Les Shadoks et le big blank \xbb (2000)', ...}...]

**Comment by sbraz** [comment]
Fixed in https://github.com/sbraz/pymediainfo/commit/a16e5c2d7de84d6a330eebcee97191aee227d06b
