### ISSUE TITLE
Base64 cover data for audio files no longer read with MediaInfo update

### ISSUE THREAD

**Issue by drakkar1969** [sbraz/pymediainfo#51]
With a recent update of MediaInfo, base64 cover data is no longer output unless the following switches are used:
`mediainfo --Full --Cover_Data=base64`

More on this issue: [https://sourceforge.net/p/mediainfo/discussion/297610/thread/aeb4222d/?limit=25](url)

Is there any way to set options in pymediainfo?

**Comment by sbraz** [comment]
Hi, there is no way to pass options to MediaInfo but I will add a `cover_data` parameter ASAP :)
PS: your URL seems broken:
```html
<a href="url">https://sourceforge.net/p/mediainfo/discussion/297610/thread/aeb4222d/?limit=25</a>
```

**Comment by drakkar1969** [comment]
Thanks for the quick response - and for the pymediainfo wrapper :)

Trying link again: [Sourceforge](https://sourceforge.net/p/mediainfo/discussion/297610/thread/aeb4222d/)

**Comment by sbraz** [comment]
Leaving this link here so I can easily find it later: https://github.com/MediaArea/MediaInfoLib/commit/d8fd88a1c282d1c09388c55ee0b46029e7330690
I will only pass this option starting with version 18.03 of the library.

Yup, link works this time :)

**Comment by drakkar1969** [comment]
Awesome, thanks

**Comment by sbraz** [comment]
Can you try the `coverdata` branch? You need to pass `cover_data=True` to the `parse` function.

**Comment by drakkar1969** [comment]
Works like a charm

**Comment by sbraz** [comment]
Cool :) Let me add tests for this feature and I'll merge to the master branch and release a new version.

**Comment by JeromeMartinez** [comment]
I was not aware that cover data was so used (I implemented that a long time ago, for a specific need), good to know because I really thought that nobody uses it and that this change would not have impact on so many people.
