### ISSUE TITLE
Parsing fails after XPath change

### ISSUE THREAD

**Issue by sbraz** [sbraz/pymediainfo#57]
It seems that commit e46f6dbd093e675f35319ca6408a7929550828e2 broke XML parsing for some users.
@choyj I'm opening this issue because I don't understand how the XPath change can cause things to fail for you, it's really weird.
Can you please run the following tests?
```
git clone https://github.com/sbraz/pymediainfo
cd pymediainfo
# move your example 10secfail.mp4 file here
python3 demo.py 10secfail.mp4
```
Does it work?

Then (still from the pymediainfo folder to make sure that you are loading the git version of the module, not another one):
```
python3 setup.py test
```
Do tests pass?

One last thing (still from the pymediainfo folder): I looked at that XML file which you generated and I can parse it without any problem, what happens if you do that?
```
python -c "import pymediainfo; print(pymediainfo.MediaInfo(open('10secfail.xml').read()).tracks)"
```
If it works, it will show you something like
```
[<Track track_id='None', track_type='General'>, <Track track_id='2', track_type='Video'>, <Track track_id='1', track_type='Audio'>]                                                                               
```

**Comment by choyj** [comment]
So tried all of these.  A few comments:
- `python3 demo.py 10secfail.mp4` doesn't appear to do anything for me.
- I couldn't get `python3 setup.py test` to work.  It had trouble finding `pytest`, but running `pytest` manually worked.
- When I first started debugging unicode issue, I always found it weird that I could save the OLDXML output to a file MediaInfo(open()) would work, but MediaInfo.parse() would not.
- Good files fail no tracks with what's currently in `master` due to the `File/` you added.  Removing it works for me.
Attached is the output from my run
[output.txt](https://github.com/sbraz/pymediainfo/files/2341956/output.txt)

**Comment by sbraz** [comment]
You need to install pytest-runner to make tests work from setup.py. Your
run of pytest used your globally installed and patched pymediainfo version,
hence the test failure.

But anyway, since demo.py failed, I doubt tests will pass. For some reason,
your XML parser doesn't see a File element at the top level. I'm going to
make a branch that contains debugging info and I'll make you test it.




I'm also going to try everything you did inside an Ubuntu 18 VM first and
maybe also with WSL but that will be much more work for me.

**Comment by sbraz** [comment]
I can reproduce with Ubuntu 18!

**Comment by sbraz** [comment]
There is a problem with libmediainfo on Ubuntu 18. The  XML output from my code looks like this:
```
<File>                         
<track type="General">                          
…
```
Whereas If I run `mediainfo --output=OLDXML`, the header is present:
```
<?xml version="1.0" encoding="UTF-8"?>
<Mediainfo version="17.12">
<File>
<track type="General">
…    
```

@JeromeMartinez do you have any Idea why this happens? I've run the tests with Ubuntu 18's `libmediainfo0v5:amd64` version      `17.12-1build1`.
This is my code, am I missing an option? https://github.com/sbraz/pymediainfo/blob/ed6f7ed466274a7be64c6d5f022410c31b9ff76d/pymediainfo/__init__.py#L170-L239

**Comment by choyj** [comment]
More work for you to create an Ubuntu 18 VM, but great news you were able to reproduce it!
