### ISSUE TITLE
Platform wheels

### ISSUE THREAD

**Issue by bgermann** [sbraz/pymediainfo#59]
Is there a chance to get platform wheels for at least Windows and Mac with the bundled library file on PyPI? Would you accept a PR with continuous deployment that publishes them?

**Comment by sbraz** [comment]
Hi,
I'm not really sure how to handle libmediainfo's licence, do you have any experience with that? I'm not opposed to the idea of distributing wheels but I assume they're worthless without libmediainfo.

**Comment by sbraz** [comment]
OK I see.
Where would we install libmediainfo with that wheel? Have you already created such a wheel for pymediainfo?

**Comment by bgermann** [comment]
The libmediainfo would be contained in the wheel's root with the py files. I do not have created a wheel for pymediainfo.

I checked libmediainfo's dependencies and the minimal ones are zlib and zenlib which are both under zlib license. This seems to allow removing the license from binary distributions (but not from source distributions), but I would include them anyway.

**Comment by bgermann** [comment]
The best option seems to be using libmediainfo's cmake build with the setuptools compatible https://github.com/scikit-build/scikit-build

**Comment by bgermann** [comment]
The build files have too many quirks. I created #61 that enables bundling pre-built (e.g. the officially distributed) binaries. Would you include this and publish wheels for Windows and macOS, please?

If you also want to distribute Linux builds, there is more involved, because you would have to target manylinux1 or manylinux2010. As most Linux users use their distribution's package system over pip this is probably not worth the effort.

**Comment by bgermann** [comment]
Thank you!
