### ISSUE TITLE
Exception has occurred: OSError [WinError 126] 

### ISSUE THREAD

**Issue by qqgg231** [sbraz/pymediainfo#63]
Do I need to install MediaInfo library aside from pymediainfo?

Documentation doesn't contain this information

**Comment by sbraz** [comment]
https://pymediainfo.readthedocs.io/en/stable/
> This is a simple wrapper around the MediaInfo library, which you can find at https://mediaarea.net/en/MediaInfo

The library will soon be bundled though.

**Comment by sbraz** [comment]
You're on Windows, right? You only need the DLL file.
