### ISSUE TITLE
There is no way to use ParseSpeed when parsing file

### ISSUE THREAD

**Issue by petr0ff** [sbraz/pymediainfo#65]
PROBLEM: for now there is no way to specify ParseSpeed parameter for parsing using pymediainfo. The default value which mediainfo uses is 0.5 but for 4K HDR videos it may loose some important information, for example Text streams, whereas full parse (ParseSpeed=1.0) gives all the information about the video, including the text streams
EXPECTED: have an argument in parse method that allows to set the ParseSpeed that mediainfo will use, for example `mediainfo.parse('/some/file.ts', parse_speed=1.0)`
ACTUAL: There is no way to set the ParseSpeed using pymediainfo

**Comment by sbraz** [comment]
You're absolutely right. I'll have to implement that.

**Comment by petr0ff** [comment]
@sbraz thanks for your reply! How fast can it be implemented, what do you think?

**Comment by sbraz** [comment]
It's quite fast to implement. I just need to find a test file that shows different results with and without ParseSpeed=1.

**Comment by sbraz** [comment]
Do you need a new release with the changes?

**Comment by petr0ff** [comment]
> Do you need a new release with the changes?

@sbraz yes please, we have the lib in requirements and use it on production, so would be nice to have pypi version updated after our deploy

**Comment by sbraz** [comment]
v3.1 will be released as soon as the Travis build completes :)

**Comment by petr0ff** [comment]
Supercool :) thanks again!
