### ISSUE TITLE
Source tarball generated on OSX contains renamed test file

### ISSUE THREAD

**Issue by sbraz** [sbraz/pymediainfo#67]
Tests fail for v3.2 with:
 ```
E           IOError: [Errno 2] No such file or directory: u'/var/tmp/portage/dev-python/pymediainfo-3.2/work/pymediainfo-3.2/tests/data/accentu\xe9.txt'                                                         
```

The file in the archive contains `é` which is an e with a combining acute accent (`e\xcc\x81`). It should be a normal `é`.

**Comment by sbraz** [comment]
@bgermann Do you have any idea why Travis changes the filename when it generates the sdist?

**Comment by bgermann** [comment]
No idea...

**Comment by bgermann** [comment]
Maybe it is a locale issue.

**Comment by sbraz** [comment]
I don't think I want to fight OSX. I'm just going to make the sdist on linux.
