### ISSUE TITLE
Dictionary Option

### ISSUE THREAD

**Issue by TA40** [sbraz/pymediainfo#69]
Hi,
I wanted to ask if it would be possible to add a option to output an dictionary of the full file?
I made an example for this: 
![image](https://user-images.githubusercontent.com/46388493/56999307-ea3f2880-6bae-11e9-86a1-176aa056f135.png)

try it with this code on http://json.parser.online.fr/
```
{
"video":{"0":{"fps":"23.976","height":"720","width":"1080"}},
"audio":{"0":{"lang":"ger","bitrate":"128 kbps"},"1":{"lang":"eng","bitrate":"256 kbps"}}
}
```

I would really appreciate that, this would also be much easier for me :)

**Comment by sbraz** [comment]
`pymediainfo.MediaInfo.parse("somefile").to_json()`?
https://github.com/sbraz/pymediainfo/blob/9aa65d8387723e6c32c1570d67c4c9c019ad3cbc/pymediainfo/__init__.py#L314

**Comment by TA40** [comment]
Oh, I am blind as hell. Don't know how I oversaw that, sorry ^^ Thank you very much!
