### ISSUE TITLE
libmediainfo.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ddi98** [sbraz/pymediainfo#84]
Hi, when I try to open a file I am returned the following error:
libmediainfo.so.0: cannot open shared object file: No such file or directory

`media_info = MediaInfo.parse('viamarconi.wav')

durata = (media_info.tracks[0].duration / 1000.0)`

using ubuntu 18.04, pymediafile is installed inside a virtual venv environment

**Comment by sbraz** [comment]
Hi,
As stated in the documentation, this is a wrapper around the MediaInfo library. If you don't have it installed, it will fail. Please install `libmediainfo0v5` and try again.

**Comment by sbraz** [comment]
I'm closing this since you didn't reply. Let me know if I need to reopen this issue.

I have updated the documentation to make it very clear that the library is required:


![image](https://user-images.githubusercontent.com/4833332/80923199-736cda80-8d82-11ea-9403-555c1fe6c7ec.png)

**Comment by ndyanx** [comment]
Failed in termux: "library "libmediainfo.so.0" not found"
`pkg install libmediainfo`  `pkg install mediainfo`
```
@staticmethod
def _get_library_paths(os_is_nt: bool) -> Tuple[str]:
    if os_is_nt:
        library_paths = ("MediaInfo.dll",)
    elif sys.platform == "darwin":
        library_paths = ("libmediainfo.0.dylib", "libmediainfo.dylib")
    else:
        library_paths = ("libmediainfo.so.0",)
    script_dir = os.path.dirname(__file__)
    # Look for the library file in the script folder
    for library in library_paths:
        absolute_library_path = os.path.join(script_dir, library)
        if os.path.isfile(absolute_library_path):
            # If we find it, don't try any other filename
            library_paths = (absolute_library_path,)
            break
    # patch for Termux
    termux_path = "/data/data/com.termux/files/usr/lib/libmediainfo.so"
    if os.path.isfile(termux_path):
        library_paths = (termux_path,)
    return library_paths

```

**Comment by sbraz** [comment]
@ndyanx see #134.
