### ISSUE TITLE
Cannot find libmediainfo shared library

### ISSUE THREAD

**Issue by RememberTheAir** [sbraz/pymediainfo#89]
I know this is a duplicate of multiple issue (such as #84), but I can't really wrap my head around it.

So, every time I try to parse a media file, I get the following error:

`OSError: libmediainfo.so.0: cannot open shared object file: No such file or directory`

I have installed libmediainfo and bot `mediainfo` and `mediainfo-gui` work properly. I have installed libmedianfo0V5:

```bash
$ dpkg -s libmediainfo0V5
Package: libmediainfo0v5
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 7722
Maintainer: MediaArea.net SARL <info@mediaarea.net>
Architecture: amd64
Multi-Arch: same
Source: libmediainfo
Version: 20.03-1
```

I saw the library allows to pass a path to the `.so` file representing the libmediainfo library (specifically [here](https://github.com/sbraz/pymediainfo/blob/master/pymediainfo/__init__.py#L184)), which might solve my issue. I've tried to look everywhere in https://mediaarea.net/en/MediaInfo/ but I cannot find anything useful, how do I get this .so file?

**Comment by sbraz** [comment]
What distro are you using? If it's Debian/Ubuntu, you could just install their packaged `pymediainfo` and it should pull the package containing the `.so`.

**Comment by sbraz** [comment]
Just verified that on Debian Buster and Ubuntu Focal, `libmediainfo0v5` contains the library:
```
# dpkg -L libmediainfo0v5 | grep -F .so
/usr/lib/x86_64-linux-gnu/libmediainfo.so.0.0.0
/usr/lib/x86_64-linux-gnu/libmediainfo.so.0
```
If `mediainfo` works, the `.so` is probably properly installed. From dpkg's output, I guess you're using https://mediaarea.net/download/binary/libmediainfo0/20.03/libmediainfo0v5_20.03-1_amd64.Debian_10.deb which should be fine too.

If you indeed have the library installed and pymediainfo doesn't find it, it might have to do with non-standard library paths (check what's inside `/etc/ld.so.conf.d/*`).

**Comment by RememberTheAir** [comment]
I'm on popOS, which is Ubuntu-based. I tried to install python3-pymediainfo (coming from https://repology.org/project/python:pymediainfo/versions -> Ubuntu 20.10) but I'm getting the same error

**Comment by RememberTheAir** [comment]
> If you indeed have the library installed and pymediainfo doesn't find it, it might have to do with non-standard library paths (check what's inside /etc/ld.so.conf.d/*).

Will try, thanks

**Comment by sbraz** [comment]
It's weird that mediainfo finds the library but not pymediainfo. What does `ldd /usr/bin/mediainfo | grep libmediainfo.so.0` show? It should look like
```
        libmediainfo.so.0 => /lib/x86_64-linux-gnu/libmediainfo.so.0 (0x00007f7008736000)
```

**Comment by RememberTheAir** [comment]
Yes, it looks exactly like that

**Comment by sbraz** [comment]
So the file exists. Can you show me the traceback leading to the exception? What pymediainfo are you running?
What happens if you use `pymediainfo.MediaInfo.parse(path, library_file="/lib/x86_64-linux-gnu/libmediainfo.so.0")` from https://pymediainfo.readthedocs.io/en/stable/pymediainfo.html#pymediainfo.MediaInfo.parse?

**Comment by RememberTheAir** [comment]
Btw after copying the .so file directly into the project dir, now I get the same error for libzen:

`OSError: libzen.so.0: cannot open shared object file: No such file or directory`

**Comment by sbraz** [comment]
Do not copy the file to the project directory, this is not needed, [ctypes](https://docs.python.org/3/library/ctypes.html) should find the library like the mediainfo binary does. Are you using a custom python version or something? Does `python -c 'import ctypes; ctypes.CDLL("libmediainfo.so.0")'` work (no output) or does it fail with an exception?

**Comment by RememberTheAir** [comment]
Full traceback:

```
Traceback (most recent call last):
  File "/home/chemp/PycharmProjects/dir-scan/01_library.py", line 216, in <module>
    main()
  File "/home/chemp/PycharmProjects/dir-scan/01_library.py", line 211, in main
    analyze_path(path_to_walk)
  File "/home/chemp/PycharmProjects/dir-scan/01_library.py", line 157, in analyze_path
    media_info = utils.load_mediainfo(movie_file_path)  # create the mediainfo file if it doesn't exist (never refresh it if it exists)
  File "/home/chemp/PycharmProjects/dir-scan/utilities.py", line 199, in load_mediainfo
    media_info = MediaInfo.parse(movie_file_path).to_data()  # to_data() converts the object to dict
  File "/home/chemp/PycharmProjects/dir-scan/venv/lib/python3.7/site-packages/pymediainfo/__init__.py", line 306, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
  File "/home/chemp/PycharmProjects/dir-scan/venv/lib/python3.7/site-packages/pymediainfo/__init__.py", line 197, in _get_library
    lib = lib_type(library)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmediainfo.so.0: cannot open shared object file: No such file or directory

Process finished with exit code 1
```

If I try to set the path to `/lib/x86_64-linux-gnu/libmediainfo.so.0`, it raises the same exception with a different path

**Comment by RememberTheAir** [comment]
> Are you using a custom python version or something?

I don't think so, I'm using the python version that was bundled in the distro. I'm running the script in a virtual env created using PyCharm

> Does python -c 'import ctypes; ctypes.CDLL("libmediainfo.so.0")' work (no output) or does it fail with an exception?

It actually works :thinking:

**Comment by sbraz** [comment]
Try without the virtual env please. Maybe it blocks outside libs.

**Comment by RememberTheAir** [comment]
Configuring the project to run with the interpreter in `/usr/bin/` will result in the same error, but if I run it from the terminal and not from withing PyCharm it works, so it looks like it's a issue with PyCharm

**Comment by sbraz** [comment]
It looks like other people are adding all the library paths to `LD_LIBRARY_PATH`: https://stackoverflow.com/questions/33812902/pycharm-cannot-find-library

It seems weird that this is required. Maybe you should open an issue with PyCharm.

**Comment by RememberTheAir** [comment]
Did run the thing outside PyCharm and it works correctly. Definitely an issue with PyCharm. Thanks a lot of the great support
