### ISSUE TITLE
How do I set mediainfo ?

### ISSUE THREAD

**Issue by cocos56** [sbraz/pymediainfo#97]
Can pymediainfo only be used to read mediainfo of media file ?

**Comment by sbraz** [comment]
Hi, I'm not sure what you mean by that, did you look at the documentation hosted at https://pymediainfo.readthedocs.io/en/stable/?

**Comment by cocos56** [comment]
I read the documentation. But I can't find how to set mediainfo. I want to set mediainfo  (such as the comment below).
![image](https://user-images.githubusercontent.com/36597804/91367018-f76a3700-e837-11ea-86d7-7312dd41cb48.png)

**Comment by JeromeMartinez** [comment]
> I wanna set the comments

MediaInfo (so pymediainfo) is currently only for reading metadata, not writing it.

**Comment by cocos56** [comment]
> > I wanna set the comments
> 
> MediaInfo (so pymediainfo) is currently only for reading metadata, not writing it.

Can you add support for setting mediainfo?

**Comment by JeromeMartinez** [comment]
> Can you add support for setting mediainfo?

[If you really want it, sure](https://mediaarea.net/Services).
More seriously, readout of a lot of formats is already an huge task, and I (the main developer of MediaInfo library, not pymediainfo) didn't yet find a way to pay the people behind the code for implementing writing.
