### ISSUE TITLE
Can not get 'Source' field of video track with relative path

### ISSUE THREAD

**Issue by AceCLee** [sbraz/pymediainfo#99]
MediaInfo GUI can parse this 'Source' field of mpls container.
![mediainfo](https://user-images.githubusercontent.com/54193973/97670398-79413f80-1ac9-11eb-973c-72d8b9b60429.png)
I can not get this field with relative path, like this:
```python
MediaInfo.parse("00001.mpls").to_data()
```
But I can get this field with absolute path, like this:
```python
MediaInfo.parse(r"D:\xxx\xxx\xxx\00001.mpls").to_data()
```

**Comment by sbraz** [comment]
Hi, I can reproduce the issue with `mediainfo 00001.mpls` and `mediainfo BDMV/PLAYLIST/00001.mpls`, meaning this is a https://github.com/MediaArea/MediaInfoLib/ issue. Please open it there.

The presence of the `Source` field is linked to the presence of `BDMV` in the path. This is probably defined [here](https://github.com/MediaArea/MediaInfoLib/blob/df913eafdb0ee7d8dba939fcc32bd35ce084dfaf/Source/MediaInfo/Multiple/File_Bdmv.cpp#L455).
